### ISSUE TITLE
OPML10Generator generateHead hasHead bug

### ISSUE THREAD

**Issue by Cimballi** [rometools/rome-opml#2]
In OPML10Generator.generateHead method, there is a bug with the way hasHead is calculated. Its value is always the value for the last element, "windowTop" in the current state. It should be a OR with the previous value.

**Comment by PatrickGotthard** [comment]
Hi Cimballi,

would you like to post some code to reproduce the issue?

Regards,
Patrick

**Comment by Athou** [comment]
I can reproduce this one. The head will not be present in the opml file at all if the windowTop attribute is not set. To reproduce, you simply need to generate an OPML file with a only a title in the head element. 

All lines with hasHead= in generateHead should be replaced with hasHead |=

**Comment by ramannanda9** [comment]
Yes, It is a bug and it is a severe bug as the output opml will not be valid without the head and hence cannot be parsed.

**Comment by PatrickGotthard** [comment]
Hi everybody,

sorry for the late response, I just relocated and have no internet so far. Would you like to create a fork of the rome-opml project, fix the issue and create a pull request? It would be great when you add a unit test for this issue too.

I'm currently very busy and have no time to fix the issue myself.

Regards,
Patrick

**Comment by Athou** [comment]
Done!

**Comment by jtsay362** [comment]
I encountered this bug as well. Hope this can be merged soon.

**Comment by PatrickGotthard** [comment]
Hi,

I just merged the fix from Athou. Currently we prepare to combine all ROME projects in the main "rome" repository so it will take another while before we create release 1.6.0 that includes the fix.

Regards,
Patrick
